### ISSUE TITLE
Audacitorch install prevents import of torchaudio

### ISSUE THREAD

**Issue by jonesmo** [hugofloresgarcia/audacitorch#9]
I've trained a model that acts on MFCCs I get using torchaudio.  When I installed audacitorch to wrap my model (in Colab), it prevents me from importing torchaudio with the message `OSError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory`.  It looks like installing audacitorch uninstalls and re-installs torch - might that have something to do with it?

**Comment by jonesmo** [comment]
Here's the full error: `/usr/lib/python3.7/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    362 
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle

OSError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory`

**Comment by hugofloresgarcia** [comment]
Hi! What version of audacitorch are you trying to use? You will probably need to use `torchaudio==0.9.0`, since audacitorch uses torch 1.9.1

**Comment by jonesmo** [comment]
Yes thanks that worked!

**Comment by hugofloresgarcia** [comment]
happy to help:)
